version: "3.2"
services:
  # Reverse proxy webserver
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      # Only nginx will have frontend accessibility
      - frontend
      - backend
    ports:
      - "8080:80"
      - "8081:81"
  # Database server
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: weakpassword
    ports:
      - "27017:27017"
    networks:
      - backend
  # Node application (access via nginx)
#  node:
#    image: node
#    volumes:
#      - ./node:/
#    networks:
#      - backend
  # Database admin panel
  mongodb-admin:
    image: mrvautin/adminmongo
    restart: always
    environment:
      - CONN_NAME=mongodb
      - DB_HOST=mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=weakpassword
      - DB_PORT=27017
      - HOST=0.0.0.0
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - backend

# Network configuration
networks:
  frontend:
  backend: